name: luss-ae-req
channels:
  - iopath
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - absl-py=0.13.0
  - astor=0.8.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=2.0.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.1
  - cryptography=3.4.7
  - cudatoolkit=11.1.1
  - cycler=0.10.0
  - daal4py=2021.3.0
  - dal=2021.3.0
  - dataclasses=0.8
  - dbus=1.13.18
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fvcore=0.1.5.post20210804
  - gast=0.5.0
  - glib=2.69.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.0.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.38.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.1
  - importlib-metadata=4.6.4
  - intel-openmp=2021.3.0
  - iopath=0.1.9
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - joblib=1.0.1
  - jpeg=9b
  - jsonpatch=1.32
  - jsonpointer=2.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - mpi=1.0
  - mpich=3.3.2
  - ncurses=6.2
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.3.0
  - openssl=1.1.1l
  - pandas=1.1.5
  - parso=0.7.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.0.1
  - portalocker=2.3.0
  - prompt-toolkit=3.0.20
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytorch=1.9.0
  - pytz=2021.3
  - pyyaml=5.4.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=3.4.2
  - scikit-learn=0.24.2
  - scikit-learn-intelex=2021.3.0
  - seaborn=0.11.2
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - tabulate=0.8.9
  - tbb=2021.3.0
  - tensorboard=1.14.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - torchaudio=0.9.0
  - torchfile=0.1.0
  - torchvision=0.10.0
  - tornado=6.1
  - tqdm=4.62.0
  - traitlets=4.3.3
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - visdom=0.1.8.9
  - wcwidth=0.2.5
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.37.0
  - wrapt=1.12.1
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - addict==2.4.0
    - antialiased-cnns==0.3
    - decorator==4.4.2
    - imageio==2.9.0
    - imgaug==0.4.0
    - mmcv-full==1.3.11
    - natsort==7.1.1
    - networkx==2.5.1
    - opencv-contrib-python==4.5.3.56
    - opencv-python==4.5.3.56
    - packaging==21.0
    - pysnooper==0.5.0
    - pywavelets==1.1.1
    - scikit-image==0.17.2
    - scipy==1.2.0
    - shapely==1.7.1
    - tensorboardx==2.4
    - tifffile==2020.9.3
    - torchsnooper==0.8
    - torchsummary==1.5.1
    - tsnecuda==0.1.1
    - yapf==0.31.0
